apiVersion: v1
kind: ServiceAccount
metadata:
  name: lucky-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lucky-scheduler-cluster-admin
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: lucky-scheduler
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lucky-scheduler-config
  namespace: kube-system
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: lucky-scheduler
    algorithmSource:
      policy:
        configMap:
          namespace: kube-system
          name: lukcy-scheduler-policy
    leaderElection:
      leaderElect: true
      lockObjectName: lucky-scheduler
      lockObjectNamespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lucky-scheduler-policy
  namespace: kube-system
data:
  policy.cfg : |
    {
      "kind" : "Policy",
      "apiVersion" : "v1",
      "extenders" : [{
        "urlPrefix": "http://localhost:8080/",
        "filterVerb": "filter",
        "prioritizeVerb": "prioritize",
        "weight": 1,
        "enableHttps": false
      }]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucky-scheduler
  namespace: kube-system
  labels:
    app: lucky-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lucky-scheduler
  template:
    metadata:
      labels:
        app: lucky-scheduler
    spec:
      serviceAccountName: lucky-scheduler
      volumes:
        - name: lucky-scheduler-config
          configMap:
            name: lucky-scheduler-config
      containers:
        - name: lucky-scheduler-ctr
          image: gcr.io/google_containers/hyperkube:v1.16.3
          imagePullPolicy: IfNotPresent
          args:
            - kube-scheduler
            - --config=/my-scheduler/config.yaml
            - -v=4
          volumeMounts:
            - name: lucky-scheduler-config
              mountPath: /lucky-scheduler
        - name: my-scheduler-extender-ctr
          image: quay.io/zerodayz/lucky-scheduler
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          ports:
            - containerPort: 8080